config/routes.rb
PlayAuth::Engine.routes.draw do
  
  devise_for  :users, 
          :controllers => { 
            :omniauth_callbacks => 'play_auth/users/omniauth_callbacks',
          }, 
          :class_name => 'PlayAuth::User',
          :module => :devise

  match '/profile' => 'users#profile', :as => 'profile'

  match '/admin' => 'admin/admin#index', :as => 'admin'
  
  match '/confirm/:confirmation_token',
      :to => 'devise/confirmations#show',
      :as => 'user_confirm', :only_path => false

  resources :users
  namespace :admin do
    resources :users
  end
end

app/models/play_auth/ability.rb
module PlayAuth
  class Ability
    include CanCan::Ability

    def initialize(user)
      user ||= PlayAuth::User.new
      unregistered

      user.roles.each { |role| send role.name.downcase }

      can :read, :all
    end

    #### ROLES ####

    def unregistered

    end


    def user
      can :profile, PlayAuth::User
    end


    def admin
      can :manage, :all
    end

  end
end

app/models/play_auth/authorization.rb
# author Naps62
module PlayAuth
  class Authorization < ActiveRecord::Base
    
    belongs_to :user

    attr_accessible :provider,
                    :uid,
                    :user_id,
                    :email,
                    :token,
                    :name,
                    :link,
                    :image_url

  end
end

app/models/play_auth/role.rb
module PlayAuth
  class Role < ActiveRecord::Base

    #### Associations ####
    # role N to N user
    has_many :role_users
    has_many :users, :through => :role_users

    #### Accessors ####
    attr_accessible :name, :desc, :users
    
  end
end

app/models/play_auth/role_user.rb
module PlayAuth
  class RoleUser < ActiveRecord::Base
    # N to N link model

    #### Relations ####

    belongs_to :user
    belongs_to :role

    #### Accessors ####
    attr_accessible :role, :user

    #### Validators ####
    validates_uniqueness_of :user_id, :scope => :role_id
  end
end

app/models/play_auth/user.rb
# author Naps62
module PlayAuth
  class User < ActiveRecord::Base

    #### Devise ####

    #include PlayAuth::Models::UserConcern
    devise  :database_authenticatable,
            :registerable,
            :encryptable,
            :recoverable,
            :rememberable,
            :trackable,
            :validatable,
            :omniauthable,
            :confirmable

    devise  :encryptor => :sha1

    #### Associations ####
    has_many :authorizations, :dependent => :destroy

    # user N to N roles
    has_many :role_users
    has_many :roles, :through => :role_users

    attr_accessible :first_name,
                    :last_name,
                    :email,
                    :password,
                    :password_confirmation,
                    :remember_me,
                    :roles,
                    :confirmed_at


    def name
      full_name = "#{first_name} #{last_name}".strip
      if full_name.size > 0
        full_name
      else
        email
      end
    end

    def admin?
      self.role?('Admin')
    end

    def role?(role)
      self.roles.where(:name => role).any?
    end
    
  end
end

app/controllers/play_auth/admin/admin_controller.rb
class PlayAuth::Admin::AdminController < PlayAuth::Admin::ApplicationController
  authorize_resource :class => 'PlayAuth::User'

  def index
  end
  
end

app/controllers/play_auth/admin/application_controller.rb
class PlayAuth::Admin::ApplicationController < PlayAuth::ApplicationController
  protect_from_forgery

  def current_ability
    PlayAuth::Ability.new(current_user)
  end
end

app/controllers/play_auth/admin/users_controller.rb
class PlayAuth::Admin::UsersController < PlayAuth::Admin::ApplicationController

  def index
    @users = PlayAuth::User.all
  end

  def show
    @user = PlayAuth::User.find params[:id]
    @providers = @user.authorizations.map(&:provider)

    render 'play_auth/users/show'
  end

  def edit
    @user = PlayAuth::User.find params[:id]
  end

  def destroy
    PlayAuth::User.find(params[:id]).destroy
    redirect_to :action => 'index'
  end
  
end

app/controllers/play_auth/application_controller.rb
class PlayAuth::ApplicationController < ::ApplicationController
		
		def resource_name
			:user
		end

		def resource
			@resource ||= PlayAuth::User.new
		end

		def devise_mapping
			@devise_mapping ||= Devise.mappings[:user]
		end

		def current_ability
			PlayAuth::Ability.new(current_user)
		end

	end

app/controllers/play_auth/users/omniauth_callbacks_controller.rb
# @autor Naps62
class PlayAuth::Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController

	# auth for facebook
	def facebook
		oauthorize 'Facebook'
	end

	# auth for google
	def google
		oauthorize 'Google'
	end

	def passthru
		render :file => "#{Rails.root}/public/404.html", :status => 404, :layout => false
	end

	# auth (generic)
	# find user that matches oauth request
	def oauthorize(kind)
		current_user ||= (params[:user]) ? PlayAuth::User.find(params[:user]) : nil
		@user = find_for_oauth(kind, request.env['omniauth.auth'], current_user)

		flash[:notice] = I18n.t 'devise.omniauth_callbacks.success', :kind => kind

		# TODO this is probably not necessary. only uid/email should be necessary to identify user. All the rest is already on DB
		session["devise.#{kind.downcase}_data"] = request.env['omniauth.auth']

		if @user.persisted?	
			#sign_in_and_redirect @user, :event => :auth
			sign_in @user, :event => :auth
		else
			#sign_in_and_redirect @user, :event => :first_auth
			sign_in @user, :event => :first_auth
		end

		# TODO this should be updated to a smarter redirect
		redirect_to main_app.root_path

	end

	#
	# private methods
	#
	private

		def find_for_oauth(provider, token, resource = nil)
			auth_data = get_auth_data(provider, token)

			# get the user associated with this auth_data, either by email or by uid
			if resource.nil?

				# try to find registered user, either by email or by uid
				if auth_data[:email]
					user = find_for_oauth_by_email(auth_data[:email])
				elsif auth_data[:uid]
					user = find_for_oauth_by_uid(auth_data[:uid])
				end

			else

				# if no matching user is registered, current resource is used
				# (might be an unpersisted User.new)
				user = resource
			end

			# persist the user unless it already is
			unless user.persisted?
				user.save
			end

			# get the identity used by the user to sign_in
			auths = user.authorizations

			if !auths.nil?
				auth = auths.find_by_provider_and_uid(provider, auth_data[:uid])
			end

			# if no identity is found, it is built
			if auth.nil?
				auth = user.authorizations.build(:provider => provider, :uid => auth_data[:uid])
			end
			auth.update_attributes auth_data

			return user
		end

		# auth data independent from provider
		def get_auth_data(provider, token)
			case provider
				when 'Facebook'
					return {
						:uid      	=> token['uid'],
						:token    	=> token['extra']['raw_info']['token'],
						:email    	=> token['extra']['raw_info']['email'],
						:name     	=> token['extra']['raw_info']['name'],
						:link     	=> token['extra']['raw_info']['link'],
						:image_url	=> token['image']
					}

				when 'Google'
					return {
						:uid    => token['uid'],
						:token  => token['credentials']['token'],
						:email  => token['info']['email'],
						:name   => token['info']['name']
					}
				else
					raise "Provider #{provider} not handled"
			end
		end

		def find_for_oauth_by_uid(uid)
			user = nil
			if auth = PlayAuth::Authorization.find_by_uid(uid.to_s)
				user = auth.user
			end
			return user
		end

		def find_for_oauth_by_email(email)
			if user = PlayAuth::User.find_by_email(email)
				user
			else
				user = PlayAuth::User.new :email => email, :password => Devise.friendly_token[0,20]
			end
		end

end

app/controllers/play_auth/users_controller.rb
#require_dependency "play_auth/application_controller"

module PlayAuth

  class UsersController < PlayAuth::ApplicationController
    load_and_authorize_resource :class => 'PlayAuth::User'

    def index
    end

    def show
      @user = PlayAuth::User.find params[:id]
      @providers = @user.authorizations.map(&:provider)
    end

    def profile
      @user = current_user
      @providers = @user.authorizations.map(&:provider)
      render :show
    end

  end
end

app/helpers/play_auth/application_helper.rb
module PlayAuth
  module ApplicationHelper
  end
end

app/helpers/play_auth/users_helper.rb
module PlayAuth
  module UsersHelper
  end
end

app/views/play_auth/admin/admin/index.html.slim
ul.actions
  = link_to 'User Management', admin_users_path

app/views/play_auth/admin/users/edit.html.slim
h2 User Edit

= form_for @user, :url => admin_user_path(@user), :html => { :method => :put } do |f|
  = devise_error_messages!

  .field
    = f.label       :email
    = f.email_field :email

  .field
    = f.label      :first_name
    = f.text_field :first_name

  .field
    = f.label      :last_name
    = f.text_field :last_name

  .field
    = f.label          :password
    = f.password_field :password, :autocomplete => :off

  .field
    = f.label          :password_confirmation
    = f.password_field :password_confirmation, :autocomplete => :off

  .field
    = f.label          :current_password
    = f.password_field :current_password

  .actions
    = f.submit 'Update'
    = link_to 'Delete account', admin_user_path(@user), :method => :delete, :data => { :confirm => 'Are you sure' }
    = link_to 'Back', :back

app/views/play_auth/admin/users/index.html.slim
.play_auth-users
  - @users.each do |user|
    = link_to user.name, user_path(user), :method => :get
    span.actions
      = link_to 'Edit', edit_admin_user_path(user)
      = link_to 'Delete', admin_user_path(user), :method => :delete

app/views/play_auth/shared/_nav.html.haml
%ul#play_auth-nav
	- if user_signed_in?
		%li= link_to t('play_auth.links.profile'), play_auth.profile_path
		%li= link_to t('play_auth.links.edit'), play_auth.edit_user_registration_path
		%li= link_to t('play_auth.links.sign_out'), play_auth.destroy_user_session_path, :method => :delete

	- else
		%li= link_to t('play_auth.links.log_in'), play_auth.new_user_session_path
		%li= link_to t('play_auth.links.sign_up'), play_auth.new_user_registration_path
		%li= link_to t('play_auth.links.forgot'), new_password_path(:user)
		/%li= #link_to t('play_auth.links.confirmation'), new_confirmation_path(resource_name)

		- PlayAuth::User.omniauth_providers.each do |provider|
			%li= link_to 'Sign in with ' + provider.to_s.titleize, "/users/auth/#{provider}", :id => "#{provider.to_s}" #omniauth_authorize_path(PlayAuth::User.new, provider), :id => "{provider.to_s}" #link_to 'Sign in with ' + provider.to_s.titleize, omniauth_authorize_path(PlayAuth::User.new, provider), :id => "#{provider.to_s}"

app/views/play_auth/shared/_nav.html.slim
header
  h1 NAV

ul#play-auth-nav
  - if user_signed_in?
    li= link_to t('play_auth.links.profile'),  play_auth.profile_path(current_user)
    li= link_to t('play_auth.links.edit'),     play_auth.edit_user_registration_path
    li= link_to t('play_auth.links.sign_out'), play_auth.destroy_user_session_path, :method => :delete

    - if current_user.admin?
      li= link_to 'Admin', play_auth.admin_path

  - else
    li= link_to t('play_auth.links.log_in'),  play_auth.new_user_session_path
    li= link_to t('play_auth.links.sign_up'), play_auth.new_user_registration_path
    li= link_to t('play_auth.links.forgot'),  new_password_path(:user)

app/views/play_auth/users/_user.html.slim
/ args:
    user


#field
  | Name: #{user.name}

#field
  | Roles:
  ul.user-roles
    - user.roles.each do |role|
      li= role.name.titleize

.field
  | Accounts:
  ul.user-authorizations
    - user.authorizations.each do |auth|
      li= "#{auth.provider.titleize} [#{auth.email}, #{auth.id}]"

app/views/play_auth/users/edit.html.slim
= current_user.name

app/views/play_auth/users/index.html.slim
h2 Users Index

app/views/play_auth/users/show.html.slim
= render 'play_auth/users/user', user: @user